theme: jekyll-theme-midnight
title: Ava's Individual Repository
description: "This GitHub project is the individual respository for Ava Brooks for trimester 3 of AP Computer Science A(Data Structures 2). This page is a 'GitHub Pages' website and contains guidance and development activities.   Cloning the GitHub Project provides Java-Spring webserver code.  Explore this page for activities. including procedures to develop, build, and deploy a Web Server."
email: "ava@gmail.com"
webserver: "avabrooks.avarepo.com"
twitter: "twitter.com/avaheartstap"
